apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-135109-gd47-service
spec:
  selector:
    app: enterprise-system-135109-gd47
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
